---
abstract: 'Shell completion routines using Rinci metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  File::Which: 0
  IO::Handle: 0
  IPC::Open3: 0
  Perinci::Sub::Wrapper: 0.47
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-Complete
requires:
  Log::Any: 0
  Perinci::Sub::GetArgs::Argv: 0.13
  Rinci: v1.1.10
  SHARYANTO::Complete::Util: 0
  UUID::Random: 0
  experimental: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perinci-Sub-Complete
  homepage: https://metacpan.org/release/Perinci-Sub-Complete
  repository: git://github.com/sharyanto/perl-Perinci-Sub-Complete.git
version: 0.35
